GET http://localhost:8080/posts


### Register user
POST http://localhost:8080/registriere
Content-Type:application/json

{
  "username": "adam",
  "password": "12345",
  "passwordBestätigung": "123"
}

### Get Kommentare
GET http://localhost:8080/kommentare/1


### Login user
POST http://localhost:8080/login
Content-Type:application/json

{
"username": "adam",
"password": "12345"
}

### Logout user
POST http://localhost:8080/logout
Content-Type:application/json

### Get user information
GET http://localhost:8080/user
Content-Type:application/json

### Get current rank for user
GET http://localhost:8080/rank

###