GET http://localhost:8080/artikelliste


### Register user
POST http://localhost:8080/registriere
Content-Type:application/json

{
  "username": "adam",
  "password": "123456",
  "passwordBestätigung": "123456",
  "email": "abd@def.de"
}


###Setze als Admin
GET http://localhost:8080/setzealsadmin/3

### Get Kommentare
GET http://localhost:8080/kommentare/1


### Login user
POST http://localhost:8080/login
Content-Type:application/json

{
"username": "adam",
"password": "12345"
}

### Logout user
POST http://localhost:8080/logout
Content-Type:application/json

### Get user information
GET http://localhost:8080/user
Content-Type:application/json

### Get current rank for user
GET http://localhost:8080/rank

### Füge einen Kommentar zu einem Artikel hinzu
POST http://localhost:8080/pluskommentar
Content-Type: application/json

{
  "id": 1,
  "text": "Kommentar 1",
  "user": {
    "id": 1,
    "username": "user1",
    "email": null,
    "admin": false
  },
  "artikel": {
    "id": 1,
    "user": {
      "id": 1,
      "username": "user1",
      "email": null,
      "admin": false
    },
    "titel": "was geht",
    "text": "hey",
    "url": "hdhhdah",
    "erstelltAm": "2023-11-16T11:05:14.090036"
  },
  "erstelltAm": "2023-11-16T11:05:14.092034"
}

### Register second user
POST http://localhost:8080/registriere
Content-Type:application/json

{
  "username": "eva",
  "password": "123456",
  "passwordBestätigung": "123456",
  "email": "abd@def.de"
}

### Lösche Artikel
DELETE http://localhost:8080/artikel/2

### Lösche Kommentar
DELETE http://localhost:8080/kommentar/3